version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8001
    depends_on:
      - auth-service

  auth-service:
    build: ./backend/auth-service
    ports:
      - "8001:8000"
    volumes:
      - ./backend/auth-service:/app
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000